### ISSUE TITLE
TRANSACTION FAILED CREATING DAO. HIGH GAS.

### ISSUE THREAD

**Issue by unicommaster** [aragon/aragon-apps#1237]
Transaction failed creating DAO. Cost me 0.8ether.

Help please.

https://etherscan.io/tx/0x180f89f871d5c8205300f14aabeef19592d111c97a9c38dd5912a8e589fc6d7d

**Comment by sohkai** [comment]
Hi @unicommaster, unfortunately that is just the expected behaviour of Ethereum once you get to large inputs. Rather than minting all the tokens in one go from the organization's creation (I notice you have ~50), it is recommended to start relatively small (5-10), and continue minting tokens once the organization has been created.
