### ISSUE TITLE
App not serving script

### ISSUE THREAD

**Issue by jvluso** [aragon/aragon-apps#239]
I'm trying to run Aragon locally. When I do, the main aragon app cannot get the scripts from the other apps. The error being thrown by the main app in the browser is:

`Failed to load Voting(0x9b061Cc570950952ccfD2B7df4c3B7FF94904e65)'s script (/script.js):  
Response { type: "cors", url: "http://localhost:3001/script.js", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, bodyUsed: false }
index.js:2284`

The error thrown by the app where it is running is:

`Proxy error: Could not proxy request /script.js from localhost:3001 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).`

**Comment by onbjerg** [comment]
Are you trying to run the app locally pointing to Rinkeby, or trying to run it locally pointing to testrpc?

**Comment by sohkai** [comment]
Hey @jvluso, this sounds like a CORS / local dev server issue, which is weird.

A few questions, since there's a number of different things that could be going on:

- Are the local apps on a fresh clone from the current master?
- Which directory are you running the apps from, is it inside the app's `app/` folder (e.g. you should be running `npm run start` in `aragon-apps/apps/voting/app`)?
- Is `localhost:3001` the `aragon-apps/apps/voting/app` server (hitting it should show just the voting UI)?
- Which version of react scripts are the local apps' using? (Probably easiest is looking inside the app's `app/`'s `package.json`, e.g. `aragon-apps/apps/voting/app/package.json`; what's the entry for `react-scripts`?) Is it `@aragon/react-scripts`?
- Does the app at app.aragon.one work for fetching scripts?

**Comment by jvluso** [comment]
- I am pointing at Rinkeby right now.
- This is a fresh clone of master
- I am running from aragon-apps/apps/voting/app
- It is serving the html properly, and I can see the app, it just always says "nothing here" because the script isn't getting fetched
- "@aragon/react-scripts": "^1.1.0-aragon.4"
- Yes. When I point it at finance.aragonpm.com it works

**Comment by sohkai** [comment]
Hmm, this is super super weird. Does `http://localhost:3001/script.js` give you anything back? Does `app/public/script.js` exist? Do any of the other local apps work or is it just Voting?

Otherwise, if it's working with `<app>.aragonpm.com`, I can only guess it's something funny with the webpack dev server that's used in our fork of react-scripts. Our fork has explicitly enabled CORS on it, so it shouldn't be a CORS issue :(.

Which OS are you running on? Most of us are using macOS, but maybe on windows or linux the dev server behaves differently / is buggy? Otherwise, you could try `yarn` if you haven't already, since the lock file might mitigate against any new updates in react-scripts' dependencies.

**Comment by jvluso** [comment]
Script.js was being called Script.js.js. Renaming it solved the problem. This was happening on linux. Thank you for helping me.

**Comment by marc4gov** [comment]
Seems I have a CORS issue, reaching out to IPFS when following the tutorial (Bella 0.7). The Counter App doesn't show in the left pane, but it is listed as 'Unknown' when I follow the `Permissions` link
<img width="1435" alt="Schermafbeelding 2019-05-22 om 08 11 27" src="https://user-images.githubusercontent.com/9572139/58151232-53273700-7c69-11e9-99c8-3fe90d947094.png">
<img width="1428" alt="Schermafbeelding 2019-05-22 om 08 11 49" src="https://user-images.githubusercontent.com/9572139/58151246-5cb09f00-7c69-11e9-9587-69a24f77d295.png">

**Comment by onbjerg** [comment]
@marc4gov Seems like it's a bug in [Aragon CLI](https://github.com/aragon/aragon-cli). I think you'll find better answers there
