### ISSUE TITLE
Assign Token action is not creating a transaction

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#265]
Window closes automatically and does not initiate signing.

Firefox - PC

Chrome - Mac

**Comment by izqui** [comment]
Do you recall if this was happening in a multisig org? I think it may have been caused by trying to assign a token to a holder that already had one (and there is a limit of just one token per holder in multisig DAOs).

If that was the case, it will be solved with #291, which will provide a warning or disallow the assign action if we know it is going to fail for this reason.

**Comment by john-light** [comment]
I do not recall and I apologize for not documenting that detail when the issue was first reported. If I had to guess, I would say yes. Go ahead and link #291 to close this issue and if it gets reported again afterwards then we can reopen or create a new issue.
