### ISSUE TITLE
NFT Vault app smart contracts

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#44]
[ERC721](https://github.com/ethereum/EIPs/issues/721) defines the standard for Non-Fungible Tokens (NFTs). By supporting ERC721 Aragon organizations will be able to manage NFTs.

Decentraland's [LAND](https://github.com/decentraland/land) and Cryptokitties both use ERC721 NFTs and seems like it will become the standard for future tokens.

Check the [Token Vault](https://github.com/aragon/aragon-apps/tree/master/apps/vault) for reference and inspiration

**Comment by onbjerg** [comment]
No need to mention LAND, you got me when you said I could manage my crypto kitties in Aragon

**Comment by onbjerg** [comment]
This should probably also be reflected in the finance app somehow, or maybe we need a separate app for NFTs. What do you think would make more sense?

Given NFTs will rarely be used in a budget, it probably makes more sense to have a dedicated NFT app to list your NFTs.

Thankfully, ERC721 specifies names, descriptions and images for the different NFTs, so it would probably be trivial to list them at least.

**Comment by sohkai** [comment]
> It probably makes more sense to have a dedicated NFT app to list your NFTs.

I totally agree. I highly doubt NFTs will be used to manage anything financial, in the way the current finance app works (accounting for payments in and out). Maybe something like "Assets" that sits alongside Tokens?

**Comment by onbjerg** [comment]
I like the name "Assets" except assets could also cover cash reserves, so it might be confusing.

**Comment by izqui** [comment]
ERC721 was just merged. We need an ERC721 vault :) https://github.com/ethereum/EIPs/pull/841

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0xbc8e96e851fb113943fb6d55493f541eb149b0fa](https://etherscan.io/address/0xbc8e96e851fb113943fb6d55493f541eb149b0fa)
![QR Code](https://openbounty.status.im/qr/aragon/aragon-apps/bounty/44/5ac6bd8f22623291fba175a17cbf44c81ae7045882fd5e79f1218b949f2e4b54/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by fcolavecchia** [comment]
Hi!, a very interesting problem, I would give it a try, if none at the core team is able to do it. The idea would be to borrow the [ERC721 standard implementation from our zeppelin cousins](https://github.com/spalladino/zeppelin-solidity/tree/feature/full_erc721/contracts/token/ERC721), and build the NTF Vault (Inventory app?) from there, adding the basic functionality.  
Sounds ok, @izqui ?
