### ISSUE TITLE
Clarify "Quorum" in Vote app

### ISSUE THREAD

**Issue by jounih** [aragon/aragon-apps#464]
Quorum is currently difficult to understand.

To make it easier for users to grasp, I'd like to propose the following:

-Separate the two graphs - voting results and quorum.
-Move the Quorum graph to the top, with the Quorum %
-Instead of naming it "Quorum" - which it strictly speaking isn't, since it only tracks absolute "Yes" percentage of total token supply, let's call it "Total Support", with more explanation in the info tooltip.
-Show if the vote will pass with a green tick and "Vote will pass" text, if both Total Support and 50%+ "Yes" vote conditions are met

Design:

![webapp-1366px - vote panel card view 2x](https://user-images.githubusercontent.com/10109867/45961302-117cb880-c016-11e8-9750-8f907e799d2c.jpg)

**Comment by bpierre** [comment]
Do we want to display “vote will pass” (or an equivalent) on the card itself?

**Comment by jounih** [comment]
Yeah we could show it maybe top right with a tick, same way like it says "Executed" for past votes

**Comment by sohkai** [comment]
On the label underneath "time remaining":

There are three states the vote can be in: "won't pass", "will pass when time ends", and "passed (can be executed)". Due to that, I'd suggest the label be "Vote will pass when time ends".

We could also use that label to say "Can be executed" after a vote's timed out, or if a vote's still open, but can be executed (right now the frontend automatically executes, but we've recently added support in the contracts so that a user doesn't have to pay the gas of executing if they just want to vote).

**Comment by jounih** [comment]
In the "Open votes" section of the UI we only have two possible states - will pass/won't pass. Since won't pass is the default, for the sake of simplicity, either show nothing, or "Vote will pass" with a tick.

**Comment by bpierre** [comment]
Done, waiting for review https://github.com/aragon/aragon-apps/pull/467

**Comment by chris-remus** [comment]
@izqui Will review.

**Comment by chris-remus** [comment]
@izqui will test.

**Comment by sohkai** [comment]
Closed by #467.
