### ISSUE TITLE
Deprecate Group app

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#54]
#51 + #52 + #53 allow the same functionality as the current Group app, plus a multisig (closes #17) and different board structures when combined with a voting app. All this, plus removing a lot of code!

Membership to a group would be expressed by ownership of a non-transferable token. Actions as a group member can be forwarded with the forward function of the token manager!

Note: will also close #35.

**Comment by shyblugs** [comment]
So what is the difference between a board and a multisig?

**Comment by izqui** [comment]
In my mind, in a board different addresses could have different vote weights. A board where everyone has the same weight would effectively be a multisig.

**Comment by shyblugs** [comment]
That's sounds alot more flexible. So would I be right in thinking the main benefit of depreciating the groups app cuts down on gas due to removing loads of code, or is it removing the ammount of complexity

**Comment by izqui** [comment]
Wouldn't really cut down any gas, but removes a lot of code and at the same time it allows more flexible governance structures with really simple code :)

**Comment by cpurta** [comment]
I agree that this is much more flexible than the current Group implementation. That is due to it having the ability to either become a board or a multisig. Plus, who doesn't like ripping out some code. 

I am just curious on how the board implementation will work though.

For example, in a board if I am a majority holder of the token would I always be allowed to forward actions? Or rather, actions will be decided based on weighted voting of the group members based on their holding/share of tokens? The multisig just being a case of that voting system where all members voting weight (tokens) are the same.

**Comment by cpurta** [comment]
Also since membership to a group requires ownership of a token. Would membership removal involve just transferring the tokens back to the token manager contract?

**Comment by izqui** [comment]
> For example, in a board if I am a majority holder of the token would I always be allowed to forward actions?

That will depend on what is the `supportNeeded` parameter on the Voting app associated with the token. The 'board approval' action will be forwarded from the voting app, the token manager forwards 'board membership' actions.

> Would membership removal involve just transferring the tokens back to the token manager contract?

Yes. Or even better, token burning. 

https://github.com/aragon/aragon-apps/blob/9ef043337a57668cfd540675b40bc748e666a034/apps/token-manager/contracts/TokenManager.sol#L91-L98

**Comment by cpurta** [comment]
Gotcha. Was taking a look at some of your changes and saw the burn function and figured that was probably the best way for membership removal.

I like this approach and excited to see the board functionality.
