### ISSUE TITLE
Show identicons for tokenholders (and other participants in the system)

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#564]

**Comment by sohkai** [comment]
We should add the address badge to all the apps, whenever we see an address.

@bpierre @jounih I believe this is already done for the following:

- [ ] Voting
- [x] Finance (almost, I think the withdrawal panel is the only one that doesn't use the address badge since it's a text input)
- [ ] Token Manager
- [ ] Survey

**Comment by sohkai** [comment]
Fixed incrementally over time :).
