### ISSUE TITLE
Add app's address to forwarding blacklist

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#637]
Should we include an app's own address to their forwarding blacklist? It would be really awkward, but if you set an app to have a permission over itself (note that this is possible in the current UI), any caller into the forwarding interface could interact with the granted functionality.

You could argue this is actually a feature (technically allows you to enhance the forwarding scope to access protected functionality from the app itself, e.g. allow any token holder to mint new tokens), but it is a bit unintuitive and the use cases may be too contrived.

**Comment by lkngtn** [comment]
Isn't this the intended behavior? For example, it is totally reasonable to require a vote to update voting parameters or for the voting app to be its own permission manager. 

Agree that in the specific case of the token manager as a forwarder it would probably not be prudent in most cases because the token manager as a forward doesn't apply significant constraints on forwarding. However even in that case I can imagine situations where it might make sense for you to self-assign the **Assign tokens** privilege and then rely on something like voting to issue tokens periodically.

**Comment by sohkai** [comment]
I'm not sure it was the intended behaviour; at least I hadn't though very hard on it until recently.

I think it makes a lot of sense in "interactive" forwarders like the Voting app, but is more difficult to justify on "non-interactive, instantaneous" forwarders like the Token Manage or Payroll. Perhaps as we get more metadata in the future about the type of forwarding an app allows, we can show warnings in the UI for things that would be a Bad Idea<sup>TM</sup> (e.g. giving Payroll its own role to add accrued value or change salaries; in this case any employee could give themselves unlimited pay).

**Comment by sohkai** [comment]
Closing; this is a feature.
