### ISSUE TITLE
Make app storage layout more graceful to app upgrades

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#68]
See my explanation: https://youtu.be/sJ7VECqHFAg?t=9m27s

Basically convert arrays to mappings.

**Comment by aflesher** [comment]
@izqui I can take a look into this. Does this apply to all the contracts in `apps/`? If so does it make sense to break this down into smaller tasks?

**Comment by sohkai** [comment]
@aflesher I think we might hold off on this, until we're closer to a 1.0 deployment. The problem is, we've already deployed old versions of these contracts with the array structure, and so making a change now will break compatibility with them.

I've switched the tags to make this more clear, and I'll add back the `good first issue` tag when we're preparing for 1.0.
